CREATE DATABASE DeAnCongTy
GO
USE DeAnCongTy
 
GO   
	CREATE TABLE NHANVIEN
	(
		HONV VARCHAR(15),
		TENLOT VARCHAR(15),
		TENNV VARCHAR(15),
		MANV CHAR(9)NOT NULL,
		NGSINH DATETIME,
		DCHI VARCHAR(50),
		PHAI CHAR(3) ,
		LUONG FLOAT,
		MA_NQL CHAR(9),
		PHG INT ,
		
	)


GO

	
	CREATE TABLE PHONGBAN
	(
		TENPHG VARCHAR(15),
		MAPHG INT NOT NULL,
		TRPHG CHAR(9),
		NG_NHANCHUC DATETIME ,
		
	)

GO
	
	CREATE TABLE DIADIEM_PHG
	(	
		MAPHG INT  NOT NULL,
		DIADIEM VARCHAR(15) NOT NULL,
		

	)
GO
	
	CREATE TABLE PHANCONG
	(
		MA_NVIEN CHAR(9) NOT NULL,
		SODA INT NOT NULL,
		THOIGIAN FLOAT,
		
	)

GO
	
	CREATE TABLE DEAN
	(
		TENDA VARCHAR (15) ,
		MADA INT  NOT NULL,
		DDIEM_DA VARCHAR(15),
		PHONG INT ,
	)

GO
	
	CREATE TABLE THANNHAN
(
	MA_NVIEN CHAR(9)  NOT NULL,
	TENTN VARCHAR(15) NOT NULL,
	PHAI	CHAR(3),
	NGSINH	DATETIME,
	QUANHE	VARCHAR(8),
	
)

GO
-- KHI XOA BANG BANG NAO DUOC THAM CHIEU THI PHAI XOA KHOA NGOAI THAM CHIEU DEN NO RUI MOI XOA NO
-- TU "GO" CHI QUAN TRONG DOI VOI TU "USE" CON DAU KO CAN TU GO VAN CO THE CHO CHAY TOAN BO CSDL OK
-- THEM RANG BUOC KHOA CHINH CHO CAC BANG:
ALTER TABLE NHANVIEN ADD CONSTRAINT PK_MANV PRIMARY KEY (MANV)
GO
ALTER TABLE PHONGBAN ADD CONSTRAINT PK_MAPHG PRIMARY KEY (MAPHG)
GO
ALTER TABLE DIADIEM_PHG ADD CONSTRAINT PK_MAPHG_DIADIEM PRIMARY KEY (MAPHG,DIADIEM)
GO
ALTER TABLE DEAN ADD CONSTRAINT PK_MADA PRIMARY KEY (MADA)
GO
ALTER TABLE PHANCONG ADD CONSTRAINT PK_PHANCONG_MA_NVIEN_SODA PRIMARY KEY(MA_NVIEN,SODA)
GO
ALTER TABLE THANNHAN ADD CONSTRAINT PK_MANVIEN_TENTN PRIMARY KEY(MA_NVIEN,TENTN)
GO
-- THEM RANG BUOC KHOA NGOAI CHO CAC BANG :
ALTER TABLE NHANVIEN ADD CONSTRAINT FK_NHANVIEN_PHG_PHONGBAN FOREIGN KEY (PHG)REFERENCES PHONGBAN(MAPHG)
GO
ALTER TABLE NHANVIEN ADD CONSTRAINT FK_NHANVIEN_MA_NQL_NHANVIEN FOREIGN KEY(MA_NQL) REFERENCES NHANVIEN(MANV)
GO
ALTER TABLE PHONGBAN ADD CONSTRAINT FK_PHONGBAN_TRPHG_NHANVIEN FOREIGN KEY (TRPHG)REFERENCES NHANVIEN(MANV)
GO
ALTER TABLE DIADIEM_PHG ADD CONSTRAINT FK_DIEMDIEM_PHG_MAPHG_PHONGBAN FOREIGN KEY (MAPHG)REFERENCES PHONGBAN(MAPHG)
GO
ALTER TABLE DEAN ADD CONSTRAINT FK_DEAN_PHONG_PHONGBAN FOREIGN KEY (PHONG) REFERENCES PHONGBAN(MAPHG)
GO
ALTER TABLE PHANCONG ADD CONSTRAINT FK_PHANCONG_MA_NVIEN_NHANVIEN FOREIGN KEY (MA_NVIEN)REFERENCES NHANVIEN(MANV),CONSTRAINT FK_PHANCONG_SODA_DEAN FOREIGN KEY(SODA) REFERENCES DEAN(MADA)
GO
ALTER TABLE THANNHAN ADD CONSTRAINT FK_THANNHAN_MANVIEN_NHANVIEN FOREIGN KEY (MA_NVIEN)REFERENCES NHANVIEN(MANV)
GO
-- THEM RANG BUOC CHECK VAO CAC THUOC TINH CUA CAC BANG:
ALTER TABLE NHANVIEN ADD CONSTRAINT CHK_NHANVIEN_PHAI CHECK(PHAI IN('NAM','NU'))
GO
ALTER TABLE PHONGBAN ADD CONSTRAINT UNI_PHONGBAN_TENPHG UNIQUE(TENPHG)
GO
ALTER TABLE PHANCONG ADD CONSTRAINT CHK_PHANCONG_THOIGIAN CHECK (THOIGIAN IN(1,5))
ALTER TABLE PHANCONG DROP  CHK_PHANCONG_THOIGIAN
-- KIEM TRA CAU TRUC CUA BANG:
SP_HELP NHANVIEN
SP_HELP PHONGBAN
SP_HELP DIADIEM_PHG
SP_HELP PHANCONG
SP_HELP DEAN
SP_HELP THANNHAN
-- KIEM TRA CAC RANG BUOC TRONG BANG:
SP_HELPCONSTRAINT NHANVIEN
SP_HELPCONSTRAINT PHONGBAN
SP_HELPCONSTRAINT DIADIEM_PHG
SP_HELPCONSTRAINT PHANCONG
SP_HELPCONSTRAINT DEAN
SP_HELPCONSTRAINT THANNHAN
GO
ALTER TABLE PHONGBAN NOCHECK  CONSTRAINT ALL
INSERT INTO PHONGBAN VALUES ( 'Nghien cuu', 5 ,333445555,05/22/1998)
INSERT INTO PHONGBAN VALUES ('Dieu Hang',4,987987987,1995/01/01)
INSERT INTO PHONGBAN VALUES ('Quan Li',1,888665555,19/06/1981)
ALTER TABLE PHONGBAN NOCHECK CONSTRAINT ALL
GO
INSERT INTO NHANVIEN VALUES ('Nguyen','Thanh','Tung',333445555,'12/08/1955','638 Nguyen Van Cu, Q5, TP HCM','Nam',4000,888665555,5)
INSERT INTO NHANVIEN VALUES ('Bui','Ngoc','Hang',999887777,19/07/1968,'638 Nguyen Van Cu,Q5, TP HCM','Nu',25000,987654321,4)
INSERT INTO NHANVIEN VALUES ('Le','Quynh','Nhu',987654321,'06/20/1951','291 Ho Van Hue, QPN, TP HCM','Nu',43000,888665555,4)
INSERT INTO NHANVIEN VALUES ('Nguyen','Manh','Hung',666884444,'06/20/1951','957 Ba Ria, Vung Tau','Nam',38000,333445555,5)
INSERT INTO NHANVIEN VALUES ('Tran','Thanh','Tam',453453453,'07/31/1972','543 Mai Thi Luu,Q1,TP HCM','Nam',38000,333445555,5) 
INSERT INTO NHANVIEN VALUES ('Tran','Hong','Quang',987987987,03/09/1969,'980 Le Hong Phong,Q10,TPHCM','Nam',25000,333445555,4)
INSERT INTO NHANVIEN VALUES ('Pham','Van','Vinh',888665555,11/10/1937,'450 Trung Vuong,Ha Noi','Nam',55000, NULL,1)
INSERT INTO NHANVIEN VALUES ('Dinh',' Ba', 'Tien', 123456789,' 01/09/1965','731 Tran Hung Dao Q1 TP HCM' , 'Nam', 30000,333445555,5)
ALTER TABLE NHANVIEN CHECK CONSTRAINT ALL
ALTER TABLE PHONGBAN CHECK CONSTRAINT ALL



-- THEM DU LIEU VAO BANG DIADIEM_PHG: 
INSERT INTO DIADIEM_PHG VALUES(1,'TP HCM')
INSERT INTO DIADIEM_PHG VALUES(4,'HA NOI')
INSERT INTO DIADIEM_PHG VALUES(5,'VUNG TAU')
INSERT INTO DIADIEM_PHG VALUES(5,'NHA TRANG')
INSERT INTO DIADIEM_PHG VALUES(5,'TP HCM')
-- THEM DU LIEU VAO BANG NHANVIEN:

INSERT INTO NHANVIEN (HONV ,TENLOT ,TENNV , MANV , NGSINH , DCHI , PHAI ,LUONG , PHG)VALUES ('Nguyen','Thanh','Tung',333445555,'12/08/1955','638 Nguyen Van Cu, Q5, TP HCM','Nam',40000,5)
INSERT INTO NHANVIEN (HONV ,TENLOT ,TENNV , MANV , NGSINH , DCHI , PHAI ,LUONG , PHG)VALUES ('Bui','Ngoc','Hang',999887777,19/07/1968,'638 Nguyen Van Cu,Q5, TP HCM','Nu',25000,4)
INSERT INTO NHANVIEN (HONV ,TENLOT ,TENNV , MANV , NGSINH , DCHI , PHAI ,LUONG , PHG)VALUES ('Le','Quynh','Nhu',987654321,'06/20/1951','291 Ho Van Hue, QPN, TP HCM','Nu',43000,4)
INSERT INTO NHANVIEN (HONV ,TENLOT ,TENNV , MANV , NGSINH , DCHI , PHAI ,LUONG , PHG)VALUES ('Nguyen','Manh','Hung',666884444,'06/20/1951','957 Ba Ria, Vung Tau','Nam',38000,5)
INSERT INTO NHANVIEN (HONV ,TENLOT ,TENNV , MANV , NGSINH , DCHI , PHAI ,LUONG , PHG)VALUES ('Tran','Thanh','Tam',453453453,'07/31/1972','543 Mai Thi Luu,Q1,TP HCM','Nam',25000,5) 
INSERT INTO NHANVIEN (HONV ,TENLOT ,TENNV , MANV , NGSINH , DCHI , PHAI ,LUONG , PHG)VALUES ('Tran','Hong','Quang',987987987,03/09/1969,'980 Le Hong Phong,Q10,TP HCM','Nam',25000,4)
INSERT INTO NHANVIEN (HONV ,TENLOT ,TENNV , MANV , NGSINH , DCHI , PHAI ,LUONG , PHG)VALUES ('Pham','Van','Vinh',888665555,11/10/1937,'450 Trung Vuong,Ha Noi','Nam',55000,1)
INSERT INTO NHANVIEN (HONV ,TENLOT ,TENNV , MANV , NGSINH , DCHI , PHAI ,LUONG , PHG)VALUES ('Dinh',' Ba', 'Tien', 123456789,' 01/09/1965','731 Tran Hung Dao Q1 TP HCM' , 'Nam', 30000,5)

-- THEM DU LIEU VAO BANG THAN NHAN:
INSERT INTO THANNHAN VALUES(333445555,'Trinh','Nu',04/05/1986,'Con gai')
INSERT INTO THANNHAN VALUES(333445555,'Khang','Nam',10/25/1983,'Con trai')
INSERT INTO THANNHAN VALUES(333445555,'Phuong','Nu',05/03/1958,'Vo chong')
INSERT INTO THANNHAN VALUES(987654321,'Minh','Nam',02/28/1942,'Vo chong')
INSERT INTO THANNHAN VALUES(123456789,'Tien','Nam',01/01/1988,'Con trai')
INSERT INTO THANNHAN VALUES(123456789,'Chau','Nu',12/30/1988,'Con gai')
INSERT INTO THANNHAN VALUES(123456789,'Phuong','Nu',05/05/1967,'Vo chong')
-- THEM DU LIEU VAO BANG DEAN: 

INSERT INTO DEAN VALUES ('San pham X',1,'VUNG TAU',5)
INSERT INTO DEAN VALUES ('San pham Y',2,'Nha Trang',5)
INSERT INTO DEAN VALUES ('San pham Z',3,'TP HCM',5)
INSERT INTO DEAN VALUES ('Tin Hoc Hoa',10,'HA NOI',4)
INSERT INTO DEAN VALUES ('Cap Quang',20,'TP HCM',1)
INSERT INTO DEAN VALUES ('Dao Tao',30,'HA NOI',4)
-- THAM DU LIEU VAO BANG PHANCONG:

INSERT INTO PHANCONG VALUES (123456789,1,32.5)
INSERT INTO PHANCONG VALUES (123456789,2,7.5)
INSERT INTO PHANCONG VALUES (666884444,3,40.0)
INSERT INTO PHANCONG VALUES (453453453,1,20.0)
INSERT INTO PHANCONG VALUES (453453453,2,20.0)
INSERT INTO PHANCONG VALUES (333445555,2,10.0)
INSERT INTO PHANCONG VALUES (333445555,3,10.1)
INSERT INTO PHANCONG VALUES (333445555,10,10.0)
INSERT INTO PHANCONG VALUES (333445555,20,10.0)
INSERT INTO PHANCONG VALUES (999887777,30,30.0)
INSERT INTO PHANCONG VALUES (999887777,10,10.0)
INSERT INTO PHANCONG VALUES (987987987,10,35.0)
INSERT INTO PHANCONG VALUES (987987987,30,5.0)
INSERT INTO PHANCONG VALUES (987654321,30,20.0)
INSERT INTO PHANCONG VALUES (987654321,20,15.0)
INSERT INTO PHANCONG VALUES (888665555,20,NULL)
--UPDATE BANG NHANVIEN:

UPDATE NHANVIEN SET MA_NQL ='333445555' WHERE MANV = 123456789
UPDATE NHANVIEN SET MA_NQL =888665555 	WHERE MANV = 333445555
UPDATE NHANVIEN SET MA_NQL = 987654321 WHERE MANV =999887777
UPDATE NHANVIEN SET MA_NQL = 888665555 WHERE MANV = 987654321
UPDATE NHANVIEN SET MA_NQL = 333445555 WHERE MANV=666884444
UPDATE NHANVIEN SET MA_NQL = 333445555 WHERE MANV = 453453453
UPDATE NHANVIEN SET MA_NQL = 987654321 WHERE MANV=987987987
--UPDATE BANG PHONGBAN:
UPDATE PHONGBAN SET TRPHG=333445555 WHERE MAPHG=5
UPDATE PHONGBAN SET TRPHG=987987987 WHERE MAPHG=4
UPDATE PHONGBAN SET TRPHG=888665555 WHERE MAPHG=1




use DeAnCongTy

/* Truy vấn đơn giản */
/* 1. Tìm các nhân viên làm việc ở phòng số 4 */
SELECT * 
FROM NHANVIEN
WHERE PHG = 4 

/* 2. Tìm các nhân viên có mức lương trên 30000 */
SELECT *
FROM NHANVIEN
WHERE LUONG > 30000

/* 3. Tìm các nhân viên có mức lương trên 25,000 ở phòng 4 hoặc các nhân viên có mức lương trên
30,000 ở phòng 5 */ SELECT *
 FROM NHANVIEN
 WHERE LUONG > 25000 AND PHG = 4 OR LUONG > 30000 AND PHG = 5 

/* 4. Cho biết họ tên đầy đủ của các nhân viên ở TP HCM */
SELECT (HONV + ' ' + TENLOT + ' ' + TENNV) AS HOVATEN, DCHI
FROM NHANVIEN
WHERE DCHI LIKE '%TP HCM'

/* 5. Cho biết họ tên đầy đủ của các nhân viên có họ bắt đầu bằng ký tự ‘N’ */
SELECT (HONV + ' ' + TENLOT + ' ' + TENNV) AS HOVATEN
FROM NHANVIEN
WHERE HONV LIKE 'N%'

/* 6. Cho biết ngày sinh và địa chỉ của nhân viên Dinh Ba Tien */
SELECT (HONV + ' ' + TENLOT + ' ' + TENNV) AS HOVATEN, NGSINH, DCHI
FROM NHANVIEN
WHERE HONV = 'Dinh' AND TENNV = 'Tien'

/* 7. Cho biết các nhân viên có năm sinh trong khoảng 1960 đến 1965 */
SELECT (HONV + ' ' + TENLOT + ' ' + TENNV) AS HOVATEN, NGSINH
FROM NHANVIEN
WHERE YEAR(NGSINH) BETWEEN 1960 AND 1965

/* 8. Cho biết các nhân viên và năm sinh của nhân viên */
SELECT (HONV + ' ' + TENLOT + ' ' + TENNV) AS HOVATEN, NGSINH
FROM NHANVIEN

/* 9. Cho biết các nhân viên và tuổi của nhân viên */
SELECT (HONV + ' ' + TENLOT + ' ' + TENNV) AS HOVATEN, (2019 - YEAR(NGSINH)) AS TUOI
FROM NHANVIEN

/* Truy vấn có sử dụng phép kết */
/* 10. Với mỗi phòng ban, cho biết tên phòng ban và địa điểm phòng */
SELECT T1.TENPHG, T2.DIADIEM 
FROM PHONGBAN T1, DIADIEM_PHG T2
WHERE T1.MAPHG = T2.MAPHG 

/* 28. Với mỗi phòng ban, cho biết tên phòng ban, họ tên người trưởng phòng và số lượng đề án mà
phòng ban đó chủ trì */
SELECT PB.TENPHG, 
CONCAT(NV.HONV, ' ', NV.TENLOT, ' ', NV.TENNV) TEN_TRUONGPHONG,
COUNT(DA.MADA) SL_DEAN
FROM PHONGBAN PB
	JOIN DEAN DA ON PB.MAPHG = DA.PHONG
	JOIN NHANVIEN NV ON PB.TRPHG = NV.MANV
GROUP BY PB.TENPHG, CONCAT(NV.HONV, ' ', NV.TENLOT, ' ', NV.TENNV)
/*14 Tìm tên những nữ nhân viên và tên người thân của họ */

select concat(NV.HONV, ' ',NV.TENLOT,' ',NV.TENNV) TENNV
from NHANVIEN NV
JOIN THANNHAN TN ON NV.MA_NQL=TN.MA_NVIEN
WHERE NV.PHAI='Nu'
/*15 Với mỗi nhân viên, cho biết họ tên nhân viên và họ tên người quản lý trực tiếp của nhân viên đó */
SELECT concat(NV.HONV, ' ',NV.TENLOT,' ',NV.TENNV) TENNV,concat(NQL.HONV,' ',NQL.TENLOT,' ',NQL.TENLOT) TEN_NQL
FROM NHANVIEN NV
LEFT JOIN NHANVIEN NQL ON NV.MANV=NQL.MANV
/* 16 Với mỗi nhân viên, cho biết họ tên của nhân viên đó, họ tên người trưởng phòng và họ tên người quản lý trực tiếp của nhân viên đó*/
SELECT    concat(NV.HONV, ' ',NV.TENLOT,' ',NV.TENNV) TENNV,
concat(TRP.HONV,' ',TRP.TENLOT,' ',TRP.TENLOT) TEN_TRUONGPHONG,
concat(NQL.HONV,' ',NQL.TENLOT,' ',NQL.TENNV) NQL
FROM NHANVIEN NV
LEFT JOIN NHANVIEN NQL ON NV.MANV=NQL.MANV
JOIN PHONGBAN PB ON NV.PHG=PB.MAPHG
JOIN NHANVIEN TRP ON NV.MANV=PB.TRPHG
/*
 17 Tên những nhân viên phòng số 5 có tham gia vào đề án "San pham X" và nhân viên này do "Nguyen Thanh Tung" quản lý trực tiếp. */
 select *
 from NHANVIEN nv
 join PHANCONG pc on nv.MANV=pc.MA_NVIEN
 join DEAN da on pc.SODA=	da.MADA
 join NHANVIEN nql on nv.MA_NQL=nql.MANV
 where nv.PHG=5 and da.TENDA='San pham X' 
 and concat(nql.HONV,' ',nql.TENLOT,' ',nql.TENNV)='Nguyen Thanh Tung'

 /*18. Cho biết tên các đề án mà nhân viên Đinh Bá Tiến đã tham gia. */
 select *
 from DEAN da
 join PHANCONG pc on da.MADA=pc.SODA
 join NHANVIEN nv on pc.MA_NVIEN=nv.MANV
 where concat(nv.HONV,' ',nv.TENLOT,' ',nv.TENNV)='Dinh Ba Tien'
 /*////Dạng 2 :Gom nhóm*/
 /*19. Cho biết số lượng đề án của công ty */
 select count(*) slda 
 from DEAN
 /*20 Cho biết số lượng đề án do phòng ‘Nghiên Cứu’ chủ trì */
 select count(*)
 from DEAN da
 join PHONGBAN pb on da.PHONG=pb.MAPHG
 where pb.TENPHG='Nghien Cuu'
 /*21. Cho biết lương trung bình của các nữ nhân viên */
 select AVG(nv.LUONG)
 from NHANVIEN nv
 where nv.phai='Nu'
/* 22. Cho biết số thân nhân của nhân viên ‘Đinh Bá Tiến’ */
/*23. Với mỗi đề án, liệt kê tên đề án và tổng số giờ làm việc một tuần của tất cả các nhân viên tham dự đề án đó*/
select da.TENDA,sum(pc.THOIGIAN)
from DEAN da
join PHANCONG pc on da.MADA=pc.SODA
group by da.TENDA
/*24. Với mỗi đề án, cho biết có bao nhiêu nhân viên tham gia đề án đó */
select da.TENDA,count(da.TENDA)
from DEAN da
join PHANCONG pc on da.MADA=pc.SODA
group by da.TENDA
/*25. Với mỗi nhân viên, cho biết họ và tên nhân viên và số lượng thân nhân của nhân viên đó*/
select nv.HONV,nv.TENLOT,nv.TENNV,count(nv.MANV)
from NHANVIEN nv
join PHANCONG pc on nv.MANV=pc.MA_NVIEN
group by nv.HONV,nv.TENLOT,nv.TENNV
/*29. Với mỗi phòng ban có mức lương trung bình lớn hơn 40,000, cho biết tên phòng ban và số lượng đề án mà phòng ban đó chủ trì*/
select pb.TENPHG,count(da.MADA) sl_dean
from PHONGBAN pb
join NHANVIEN nv on pb.MAPHG=nv.PHG
join  DEAN da on pb.MAPHG=da.PHONG
group by pb.TENPHG
having avg(nv.luong)>40000
/*30. Cho biết số đề án diễn ra tại từng địa điểm */
select da.DDIEM_DA,count(*) sl_da
from DEAN da
group by da.DDIEM_DA
/* bỏ câu 31 32 33 vì thiếu bảng giá trị*/
/* TRUY VẤN LỒNG + GOM NHÓM */
/*34. Cho biết danh sách các đề án (MADA) có: nhân công với họ (HONV)
 là ‘Dinh’ hoặc , có người trưởng phòng chủ trì đề án với họ (HONV) là ‘Dinh’ */
 
 select*
 from DEAN da
 where da.MADA in(
				   select pc.SODA
				 from NHANVIEN nv,PHANCONG pc
				 where nv.MANV=pc.MA_NVIEN
				 and nv.HONV='Dinh'
									 )
 or da.MADA in (
 select da.MADA
 from NHANVIEN nv,PHONGBAN pb,DEAN da
 where nv.PHG=pb.MAPHG
 and nv.MANV=pb.TRPHG
 and nv.HONV='Dinh')
 /*35. Danh sách những nhân viên (HONV, TENLOT, TENNV) có trên 2 thân nhân*/
/*Cách 1*/
 select nv.HONV,nv.TENLOT,nv.TENNV
 from NHANVIEN nv,THANNHAN tn
 where nv.MANV=tn.MA_NVIEN
 group by nv.HONV,nv.TENLOT,nv.TENNV
 having count(nv.MANV)>2
 /* Cách 2 */
 select * 
 from NHANVIEN nv
 where nv.MANV in(
 
 select tn.MA_NVIEN
 from THANNHAN tn
 group by tn.MA_NVIEN
 having count(tn.TENTN)>2
 )

 /*36. Danh sách những nhân viên (HONV, TENLOT, TENNV) không có thân nhân nào.*/
 select * 
 from NHANVIEN nv
 where nv.MANV  not in(
 
 select tn.MA_NVIEN
 from THANNHAN tn

 )
 /*37. Danh sách những trưởng phòng (HONV, TENLOT, TENNV) có tối thiểu một thân nhân */
 select nv.HONV,nv.TENLOT,nv.TENNV
 from NHANVIEN nv,PHONGBAN pb
 where nv.MANV=pb.TRPHG
 and nv.MANV in
  
	  (
	  select tn.MA_NVIEN	
	  from THANNHAN tn
	  group by tn.MA_NVIEN
	  having count(tn.TENTN)>1
	  )
 /*38. Tìm họ (HONV) của những trưởng phòng chưa có gia đình. */
 select *
 from NHANVIEN nv,PHONGBAN pb
 where nv.MANV=pb.TRPHG
 and nv.MANV not in (select tn.MA_NVIEN 
 from THANNHAN tn)
 /*39. Cho biết họ tên nhân viên (HONV, TENLOT, TENNV) có mức lương trên mức lương trung bình của phòng "Nghiên cứu" */
 select nv.HONV,nv.TENLOT,nv.TENNV
 from NHANVIEN nv
 where nv.luong>(
 select avg(nv.luong)
 from NHANVIEN nv,PHONGBAN pb
 where nv.PHG=pb.MAPHG
 and pb.TENPHG='Nghien cuu'
 )
 /*40. Cho biết tên phòng ban và họ tên trưởng phòng của phòng ban có đông nhân viên nhất. */
 select top 1  with ties pb.TENPHG,concat(trp.HONV+' ',trp.TENLOT,' ',trp.TENNV) tenNV
 ,count(nv.MANV) sl_nv
 from PHONGBAN pb
 join NHANVIEN trp on pb.TRPHG=trp.MANV
 join NHANVIEN nv on pb.MAPHG=nv.PHG
 group by pb.TENPHG,concat(trp.HONV+' ',trp.TENLOT,' ',trp.TENNV)
 order by sl_nv desc